import "./globals.css";
import Image from "next/image";
import type { Metadata } from "next";
import { Navbar } from "@/components";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} relative min-h-screen text-zinc-200 bg-[#0f0f0f]`}
      >
        <div className="px-24 container mx-auto">
          <Navbar />
          {children}
        </div>

        <Image
          priority
          fill
          sizes="100vw"
          src="/images/grid-bg.png"
          className="object-cover pointer-events-none"
          alt="grid background"
        />
      </body>
    </html>
  );
}
